# -*- coding: utf-8 -*-
"""GenDegChhatGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSBmLnp2tyFSaxhGluPc2Wf1bMaQEaES

### Aggiornare pip
"""

!pip install --upgrade pip

"""### Installare librerie"""

!pip install pandas torch transformers==4.44.2 peft==0.12.0 accelerate==0.33.0 datasets bitsandbytes sentencepiece fsspec matplotlib scikit-learn plotly

"""### Verificare librerie installate"""

import torch
import transformers
import peft
import datasets

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("Datasets:", datasets.__version__)
print("CUDA disponibile:", torch.cuda.is_available())

"""### Costruzione dei prompt per training e inferenza"""

!python pipeline_prompts.py

!python fine_tuning.py

"""### Preparazione del dataset per il training"""

!python pipeline_dataset.py

"""### Addestramento del modello con LoRA"""

!python pipeline_train_lora.py

"""### Visualizzazione dei Chunk in un grafico 3D"""

!python visualize_embeddings.py

!python example_visualize_embeddings_colab.py

"""### Generazione di schede giornalistiche per nuove degustazioni"""

!python pipeline_infer.py